name = "teaven-geo-core-service"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "teaven-geo-db"
database_id = "cb910a67-f376-4673-b568-3ed2f3728e22"

[[kv_namespaces]]
binding = "GEO_CACHE"
id = "aff987c5443c4cf2bcfe61fa8decef8f"

[vars]
CACHE_TTL = 86400
HOT_CITIES = "北京,上海,东京,New York,London,Paris,Singapore,Sydney"

[observability]
enabled = true
